#!/bin/bash

rpmbuild -bb ${WORKSPACE}/rpm.spec --define "_build_number ${BUILD_NUMBER}"
for e in $(find ~/rpmbuild/RPMS -name libmaxminddb\*.rpm); do
    //sign-rpm $e
    publish-rpm $e
    rm -f $e
done
